package com.example.capdemo.handlers;

import com.sap.cds.ql.Insert;
import com.sap.cds.ql.Select;
import com.sap.cds.services.ErrorStatuses;
import com.sap.cds.services.ServiceException;
import com.sap.cds.services.cds.CqnService;
import com.sap.cds.services.handler.EventHandler;
import com.sap.cds.services.handler.annotations.Before;
import com.sap.cds.services.handler.annotations.On;
import com.sap.cds.services.handler.annotations.ServiceName;
import com.sap.cds.services.persistence.PersistenceService;

// These imports are generated by cds-maven-plugin at build time (mvn generate-sources).
// They will show as unresolved in the IDE until the first build.
import cds.gen.userdepartmentservice.AssignUserToDepartmentContext;
import cds.gen.userdepartmentservice.Departments_;
import cds.gen.userdepartmentservice.GetUsersCountContext;
import cds.gen.userdepartmentservice.UserDepartmentService_;
import cds.gen.userdepartmentservice.UserDepartments;
import cds.gen.userdepartmentservice.UserDepartments_;
import cds.gen.userdepartmentservice.Users;
import cds.gen.userdepartmentservice.Users_;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Handles the OData Function getUsersCount() and the OData Action assignUserToDepartment().
 *
 * Input validation (mandatory fields, email format, EU country enum) is handled declaratively
 * in data-model.cds via @mandatory, @assert.format, and the EuCountry enum type (@assert.range) –
 * no Java validation code needed.
 * Spring Boot equivalent:
 *   - Simple validation → @NotBlank / @Email on DTO fields + @Valid in controller
 *   - Enum validation   → @EuCountry constraint backed by EuCountryValidator + EuCountry Java enum
 *   - Function          → GET /api/users/count in UserController
 *   - Action            → POST /api/users/{id}/assign-department in UserController
 */
@Component
@ServiceName(UserDepartmentService_.CDS_NAME)
public class UserServiceHandler implements EventHandler {

    @Autowired
    PersistenceService db;

    // -------------------------------------------------------------------------
    // COMPLEX VALIDATION – runs before CREATE and UPDATE
    // Demonstrates how domain logic validation is done via a Java handler.
    // NOTE: because address.country is typed as the EuCountry CDS enum, CAP
    // already rejects unknown values via @assert.range before this handler runs.
    // The handler is kept here to show the @Before pattern; in a real project
    // you would rely solely on the enum type and remove this handler.
    // Spring Boot equivalent: @EuCountry custom ConstraintValidator on DTO fields,
    // backed by EuCountry.valueOf() – same idea, different mechanism.
    // -------------------------------------------------------------------------

    @Before(event = {CqnService.EVENT_CREATE, CqnService.EVENT_UPDATE}, entity = Users_.CDS_NAME)
    public void validateEuCountry(Users user) {
        String country = user.getAddressCountry();
        if (country == null || country.isBlank()) return;
        // EuCountry CDS enum values are uppercase strings (GERMANY, FRANCE, …).
        // CAP already rejects unknown values via @assert.range on the enum type,
        // so this handler fires only when @assert.range is disabled or bypassed.
        // It is kept here to demonstrate the @Before validation pattern.
        if (!EU_COUNTRY_NAMES.contains(country)) {
            throw new ServiceException(ErrorStatuses.BAD_REQUEST,
                    "address.country must be a European Union member state");
        }
    }

    // Names mirror the EuCountry CDS enum declared in data-model.cds.
    private static final java.util.Set<String> EU_COUNTRY_NAMES = java.util.Set.of(
            "AUSTRIA", "BELGIUM", "BULGARIA", "CROATIA", "CYPRUS",
            "CZECHIA", "DENMARK", "ESTONIA", "FINLAND", "FRANCE",
            "GERMANY", "GREECE", "HUNGARY", "IRELAND", "ITALY",
            "LATVIA", "LITHUANIA", "LUXEMBOURG", "MALTA", "NETHERLANDS",
            "POLAND", "PORTUGAL", "ROMANIA", "SLOVAKIA", "SLOVENIA",
            "SPAIN", "SWEDEN"
    );


    // OData call:  GET /odata/v4/UserDepartmentService/getUsersCount()
    // Spring Boot: GET /api/users/count
    //
    // Functions are read-only and have no side effects (OData semantics).
    // -------------------------------------------------------------------------

    @On(event = GetUsersCountContext.CDS_NAME)
    public void getUsersCount(GetUsersCountContext ctx) {
        long count = db.run(Select.from(Users_.class).inlineCount()).rowCount();
        ctx.setResult((int) count);
        ctx.setCompleted();
    }

    // -------------------------------------------------------------------------
    // ACTION: assignUserToDepartment
    // OData call:  POST /odata/v4/UserDepartmentService/assignUserToDepartment
    // Spring Boot: POST /api/users/{id}/assign-department
    //
    // Actions can mutate state (OData semantics).
    // -------------------------------------------------------------------------

    @On(event = AssignUserToDepartmentContext.CDS_NAME)
    public void assignUserToDepartment(AssignUserToDepartmentContext ctx) {
        String userId       = ctx.getUserID();
        String departmentId = ctx.getDepartmentID();

        // Verify user exists
        if (db.run(Select.from(Users_.class).byId(userId)).rowCount() == 0) {
            throw new ServiceException(ErrorStatuses.NOT_FOUND, "User not found: " + userId);
        }

        // Verify department exists
        if (db.run(Select.from(Departments_.class).byId(departmentId)).rowCount() == 0) {
            throw new ServiceException(ErrorStatuses.NOT_FOUND, "Department not found: " + departmentId);
        }

        // Insert into the join entity. Duplicate assignment is silently ignored (idempotent).
        try {
            UserDepartments link = UserDepartments.create();
            link.setUserId(userId);
            link.setDepartmentId(departmentId);
            db.run(Insert.into(UserDepartments_.class).entry(link));
        } catch (Exception ignored) {
            // Primary key conflict – user was already assigned to this department
        }

        var result = AssignUserToDepartmentContext.ReturnType.create();
        result.setSuccess(true);
        result.setMessage("User " + userId + " assigned to department " + departmentId);
        ctx.setResult(result);
        ctx.setCompleted();
    }
}
